function Initialize-RustDefaults {
<#
.SYNOPSIS
Generates or updates global Rust configuration files with optimal defaults.
.DESCRIPTION
Creates or merges defaults into ~/.cargo/config.toml, ~/rustfmt.toml, and
~/.clippy.toml. Existing user customizations are preserved (merge-not-overwrite).
Use -Force to overwrite all values.
.PARAMETER Scope
Which configs to generate: All, Cargo, Rustfmt, or Clippy.
.PARAMETER Force
Overwrite existing values instead of merging (only adds missing keys by default).
.PARAMETER PassThru
Return generated config objects instead of just writing files.
.EXAMPLE
Initialize-RustDefaults -WhatIf
.EXAMPLE
Initialize-RustDefaults -Scope Cargo -Force
.EXAMPLE
Initialize-RustDefaults -PassThru
#>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [ValidateSet('All', 'Cargo', 'Rustfmt', 'Clippy')]
        [string]$Scope = 'All',

        [switch]$Force,

        [switch]$KeepUnsupportedGlobalRustfmtKeys,

        [switch]$PassThru
    )

    $results = [ordered]@{}

    # Resolve paths
    $cargoHome = if ($env:CARGO_HOME) { $env:CARGO_HOME } else { Join-Path $HOME '.cargo' }
    $cargoConfigPath = Join-Path $cargoHome 'config.toml'
    $rustfmtPath = Join-Path $HOME 'rustfmt.toml'
    $clippyPath = Join-Path $HOME '.clippy.toml'

    $header = 'Generated by CargoTools - safe to customize; existing values preserved on update'

    # --- Cargo config ---
    if ($Scope -eq 'All' -or $Scope -eq 'Cargo') {
        $defaults = Get-DefaultCargoConfig
        $existing = if (Test-Path $cargoConfigPath) { Read-TomlSections -Path $cargoConfigPath } else { [ordered]@{} }
        $normalization = Normalize-CargoConfigEnvTables -Config $existing
        $existing = $normalization.Config
        $unsupportedNormalization = Normalize-CargoConfigUnsupportedKeys -Config $existing
        $existing = $unsupportedNormalization.Config
        $mergeResult = Merge-TomlConfig -Existing $existing -Defaults $defaults -Force:$Force
        $toml = ConvertTo-TomlString -Data $mergeResult.Config -Header $header
        Write-ConfigFile -Path $cargoConfigPath -Content $toml

        foreach ($change in $normalization.Changes) {
            Write-Host "  cargo/config.toml: $change" -ForegroundColor Yellow
        }
        foreach ($change in $unsupportedNormalization.Changes) {
            Write-Host "  cargo/config.toml: $change" -ForegroundColor Yellow
        }
        foreach ($addition in $mergeResult.Additions) {
            Write-Host "  cargo/config.toml: $addition" -ForegroundColor Green
        }
        if ($mergeResult.Additions.Count -eq 0 -and $normalization.Changes.Count -eq 0 -and $unsupportedNormalization.Changes.Count -eq 0 -and -not $Force) {
            Write-Host "  cargo/config.toml: already up to date" -ForegroundColor Gray
        }

        $results['CargoConfig'] = [PSCustomObject]@{
            Path      = $cargoConfigPath
            Additions = $mergeResult.Additions
            Changes   = @($normalization.Changes) + @($unsupportedNormalization.Changes)
            Config    = $mergeResult.Config
        }
    }

    # --- Rustfmt ---
    if ($Scope -eq 'All' -or $Scope -eq 'Rustfmt') {
        $defaults = Get-DefaultRustfmtConfig
        $existing = if (Test-Path $rustfmtPath) { Read-TomlSections -Path $rustfmtPath } else { [ordered]@{} }
        $rustfmtBackupPath = $null
        $removedRustfmtKeys = @()
        if (-not $KeepUnsupportedGlobalRustfmtKeys -and $existing.Count -gt 0) {
            $normalizedRustfmt = Normalize-RustfmtConfig -Config $existing
            $existing = $normalizedRustfmt.Config
            $removedRustfmtKeys = @($normalizedRustfmt.RemovedKeys)
            if ($removedRustfmtKeys.Count -gt 0 -and (Test-Path -LiteralPath $rustfmtPath)) {
                $timestamp = [DateTime]::UtcNow.ToString('yyyyMMddHHmmss')
                $rustfmtBackupPath = "$rustfmtPath.cargotools.bak.$timestamp"
                Copy-Item -LiteralPath $rustfmtPath -Destination $rustfmtBackupPath -Force
            }
        }
        $mergeResult = Merge-TomlConfig -Existing $existing -Defaults $defaults -Force:$Force
        $toml = ConvertTo-TomlString -Data $mergeResult.Config -Header $header
        Write-ConfigFile -Path $rustfmtPath -Content $toml

        foreach ($removedKey in $removedRustfmtKeys) {
            Write-Host "  rustfmt.toml: removed unsupported global key '$removedKey'" -ForegroundColor Yellow
        }
        foreach ($addition in $mergeResult.Additions) {
            Write-Host "  rustfmt.toml: $addition" -ForegroundColor Green
        }
        if ($mergeResult.Additions.Count -eq 0 -and -not $Force) {
            Write-Host "  rustfmt.toml: already up to date" -ForegroundColor Gray
        }

        $results['RustfmtConfig'] = [PSCustomObject]@{
            Path        = $rustfmtPath
            Additions   = $mergeResult.Additions
            Config      = $mergeResult.Config
            RemovedKeys = $removedRustfmtKeys
            BackupPath  = $rustfmtBackupPath
        }
    }

    # --- Clippy ---
    if ($Scope -eq 'All' -or $Scope -eq 'Clippy') {
        $defaults = Get-DefaultClippyConfig
        $existing = if (Test-Path $clippyPath) { Read-TomlSections -Path $clippyPath } else { [ordered]@{} }
        $mergeResult = Merge-TomlConfig -Existing $existing -Defaults $defaults -Force:$Force
        $toml = ConvertTo-TomlString -Data $mergeResult.Config -Header $header
        Write-ConfigFile -Path $clippyPath -Content $toml

        foreach ($addition in $mergeResult.Additions) {
            Write-Host "  .clippy.toml: $addition" -ForegroundColor Green
        }
        if ($mergeResult.Additions.Count -eq 0 -and -not $Force) {
            Write-Host "  .clippy.toml: already up to date" -ForegroundColor Gray
        }

        $results['ClippyConfig'] = [PSCustomObject]@{
            Path      = $clippyPath
            Additions = $mergeResult.Additions
            Config    = $mergeResult.Config
        }
    }

    if ($PassThru) {
        return [PSCustomObject]$results
    }
}
