function Initialize-ProjectCargoConfig {
    <#
    .SYNOPSIS
    Generates a machine-specific .cargo/config.toml from detected toolchain info.
    .DESCRIPTION
    Auto-detects GPU, CUDA toolkit, MSVC, LLVM, and Windows SDK paths, then
    generates a .cargo/config.toml tailored for the current machine. Supports
    three profiles: 'full' (all settings), 'cuda' (CUDA + linker), and 'minimal'
    (linker only).

    The generated config is machine-specific and should be gitignored. Commit the
    .template file instead for reference.
    .PARAMETER Path
    Directory containing the .cargo/ folder (or where it will be created).
    Defaults to current directory.
    .PARAMETER Profile
    Configuration profile: 'full', 'cuda', or 'minimal'. Default: 'full'.
    .PARAMETER Linker
    Linker override: 'llvm-lld', 'msvc', 'rust-lld', or 'auto'. Default: 'auto'.
    .PARAMETER Force
    Overwrite existing values in config.toml.
    .PARAMETER PassThru
    Return the generated config object instead of only writing to disk.
    .EXAMPLE
    Initialize-ProjectCargoConfig -Path 'C:\codedev\pc-ai\Native\pcai_core' -Force -PassThru
    .EXAMPLE
    Initialize-ProjectCargoConfig -Profile minimal -Linker msvc
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [string]$Path = '.',
        [ValidateSet('full', 'cuda', 'minimal')]
        [string]$Profile = 'full',
        [ValidateSet('llvm-lld', 'msvc', 'rust-lld', 'auto')]
        [string]$Linker = 'auto',
        [switch]$Force,
        [switch]$PassThru
    )

    $resolvedPath = Resolve-Path -Path $Path -ErrorAction Stop
    $cargoDir = Join-Path $resolvedPath '.cargo'
    $configPath = Join-Path $cargoDir 'config.toml'

    # Detect everything
    $mc = Get-MachineConfig -Force

    # Resolve linker
    $linkerPath = switch ($Linker) {
        'llvm-lld' {
            if ($mc['LldLinkExe'] -and (Test-Path $mc['LldLinkExe'])) {
                $mc['LldLinkExe']
            } else {
                Write-Warning 'LLVM lld-link not found, falling back to auto detection.'
                $null
            }
        }
        'msvc' {
            if ($mc['MsvcLinkExe'] -and (Test-Path $mc['MsvcLinkExe'])) {
                $mc['MsvcLinkExe']
            } else {
                'link.exe'
            }
        }
        'rust-lld' {
            $bundled = Resolve-BundledRustLld
            if ($bundled) { $bundled } else {
                Write-Warning 'Bundled rust-lld not found, falling back to auto.'
                $null
            }
        }
        default { $null }  # auto
    }

    # Auto resolution: LLVM lld-link > MSVC link.exe > bundled rust-lld
    if (-not $linkerPath) {
        if ($mc['LldLinkExe'] -and (Test-Path $mc['LldLinkExe'])) {
            $linkerPath = $mc['LldLinkExe']
        } elseif ($mc['MsvcLinkExe'] -and (Test-Path $mc['MsvcLinkExe'])) {
            $linkerPath = $mc['MsvcLinkExe']
        } else {
            $bundled = Resolve-BundledRustLld
            if ($bundled) { $linkerPath = $bundled }
            else { $linkerPath = 'link.exe' }
        }
    }

    # Build config structure
    $sccacheCmd = Resolve-Sccache
    $buildSection = [ordered]@{}
    if ($sccacheCmd) { $buildSection['rustc-wrapper'] = 'sccache' }

    $targetSection = [ordered]@{
        linker = $linkerPath
    }

    $envSection = [ordered]@{}
    if ($sccacheCmd) { $envSection['RUSTC_WRAPPER'] = 'sccache' }
    $envSection['CARGO_INCREMENTAL'] = '0'

    # CUDA settings for 'full' and 'cuda' profiles
    if ($Profile -in @('full', 'cuda')) {
        if ($mc['MsvcBinDir']) {
            $envSection['NVCC_CCBIN'] = $mc['MsvcBinDir']
        }
        if ($mc['CudaComputeCap']) {
            $envSection['CUDA_COMPUTE_CAP'] = $mc['CudaComputeCap']
        }
        if ($mc['CudaPath']) {
            $envSection['CUDA_PATH'] = $mc['CudaPath']
        }
    }

    # Full profile: add sccache tuning
    if ($Profile -eq 'full') {
        $envSection['SCCACHE_SERVER_PORT'] = '4226'
        $envSection['SCCACHE_CACHE_COMPRESSION'] = 'zstd'
        $envSection['SCCACHE_DIRECT'] = 'true'
    }

    $config = [ordered]@{
        'build'                         = $buildSection
        'target.x86_64-pc-windows-msvc' = $targetSection
        'env'                           = $envSection
    }

    # Read existing and merge
    $existing = Read-TomlSections -Path $configPath
    $mergeResult = Merge-TomlConfig -Existing $existing -Defaults $config -Force:$Force

    if ($mergeResult.Additions.Count -gt 0) {
        foreach ($addition in $mergeResult.Additions) {
            Write-Verbose $addition
        }
    }

    # Generate header
    $date = Get-Date -Format 'yyyy-MM-dd HH:mm'
    $gpuName = if ($mc['GpuName']) { $mc['GpuName'] } else { 'unknown' }
    $header = "Generated by CargoTools Initialize-ProjectCargoConfig on $date`nGPU: $gpuName | Linker: $(Split-Path $linkerPath -Leaf)"

    $tomlContent = ConvertTo-TomlString -Data $mergeResult.Config -Header $header

    # Write
    if ($PSCmdlet.ShouldProcess($configPath, 'Write .cargo/config.toml')) {
        Write-ConfigFile -Path $configPath -Content $tomlContent -NoBackup:(-not (Test-Path $configPath))
        Write-Host "Wrote $configPath" -ForegroundColor Green
    }

    if ($PassThru) {
        return $mergeResult.Config
    }
}
